# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on: [ push, pull_request, workflow_dispatch ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  check-commit:
    name: check-commit
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

#      - uses: actions/checkout@v2
#        with:
#          ref: master

      - name: check-commit
        #uses: docker://haproxytech/check-commit:latest
        run: |
          env
          echo "available refs"
          git show-ref
          echo "running check"
          git clone -b target_branch_detection https://github.com/aiharos/github-actions.git
          #git clone -b master https://github.com/aiharos/github-actions.git
          cd github-actions/check-commit; go run check.go "../../."


  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          working-directory: check-commit
